DROP DATABASE IF EXISTS gross_chat;
CREATE DATABASE gross_chat;

USE gross_chat;

DROP TABLE IF EXISTS users;
CREATE TABLE users (
  id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(256) NOT NULL,
  password VARCHAR(256) NOT NULL
);
